[package]
name = "flash"
version = "0.1.0"
edition = "2021"

[lib]
name = "flash"
crate-type = ["cdylib"]

[dependencies]
cudarc = { version = "0.12", features = [
    "cublas",
    "driver",
    "cuda-version-from-build-system"
] }

[profile.release]
opt-level = 3
lto = true